name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: [ '1.18' ]  # Use latest stable Go version (equivalent to tip)
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true
    
    - name: Set up GOPATH structure
      run: |
        mkdir -p $HOME/gopath/src/golang.org/x
        cp -r . $HOME/gopath/src/golang.org/x/oauth2
        echo "GOPATH=$HOME/gopath" >> $GITHUB_ENV
        echo "$HOME/gopath/bin" >> $GITHUB_PATH
    
    - name: Get dependencies
      working-directory: ${{ env.GOPATH }}/src/golang.org/x/oauth2
      run: go get -v -t -d ./...
    
    - name: Run tests
      working-directory: ${{ env.GOPATH }}/src/golang.org/x/oauth2
      run: go test -v ./...